name: SimpleSpawnLite-Home
main: me.ellbristow.simplespawnlitehome.SimpleSpawnLiteHome
version: 1.0.2
database: true
author: ellbristow
depend: [SimpleSpawnLite-Core]
dev-url: http://dev.bukkit.org/server-mods/simplespawnlitehome
description: >
             Addon for SimpleSpawnLite. Allows the setting of Home spawn locations
commands:
  sethome:
    description: Set home location
    usage: /sethome [Home Name]
    aliases: [ssethome]
  home:
    description: Teleport to home location
    usage: /home [Home Name]
    aliases: [shome]
  removehome:
    description: Delete a home location
    usage: /removehome [Home Name]
    aliases: [remhome, delhome, sremovehome, sremhome, sdelhome]
permissions:
  simplespawn.home.*:
    description: Access to all SimpleSpawn commands
    children:
      simplespawn.home.use: true
      simplespawn.home.use.others: true
      simplespawn.home.set: true
      simplespawn.home.set.others: true
      simplespawn.home.remove: true
      simplespawn.home.remove.others: true
  simplespawn.home:
    default: op
    description: Access to /home
  simplespawn.home.others:
    default: op
    description: Can teleport to other players' /home locations
  simplespawn.home.set:
    default: op
    description: Access to /sethome
  simplespawn.home.set.others:
    default: op
    description: Access to /sethome for other players
  simplespawn.home.remove:
    default: op
    description: Access to /removehome
  simplespawn.home.remove.others:
    default: op
    description: Access to /removehome for other players
